// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Restaurante.Data;

#nullable disable

namespace Proyecto_Restaurante.Migrations
{
    [DbContext(typeof(RestauranteDalyContext))]
    [Migration("20260413042357_Subtotal")]
    partial class Subtotal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_Restaurante.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoriaId")
                        .HasName("PK__Categori__F353C1C5C1640831");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identificacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ClienteId")
                        .HasName("PK__Cliente__71ABD0A7C8BE5245");

                    b.HasIndex(new[] { "CorreoElectronico" }, "UQ__Cliente__531402F3DAC6A575")
                        .IsUnique()
                        .HasFilter("[CorreoElectronico] IS NOT NULL");

                    b.HasIndex(new[] { "Identificacion" }, "UQ__Cliente__D6F931E59FA74AC4")
                        .IsUnique()
                        .HasFilter("[Identificacion] IS NOT NULL");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Factura", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FacturaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaId"));

                    b.Property<decimal?>("Impuestos")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OrdenId")
                        .HasColumnType("int")
                        .HasColumnName("OrdenID");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("FacturaId")
                        .HasName("PK__Factura__5C0248052BBB974E");

                    b.HasIndex("OrdenId");

                    b.HasIndex(new[] { "NumeroFactura" }, "UQ__Factura__CF12F9A6B144E36E")
                        .IsUnique()
                        .HasFilter("[NumeroFactura] IS NOT NULL");

                    b.ToTable("Factura", (string)null);
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Mesa", b =>
                {
                    b.Property<int>("MesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MesaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MesaId"));

                    b.Property<int?>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroMesa")
                        .HasColumnType("int");

                    b.HasKey("MesaId")
                        .HasName("PK__Mesa__6A4196C83BEDC1B0");

                    b.ToTable("Mesa", (string)null);
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Orden", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrdenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenId"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int?>("MesaId")
                        .HasColumnType("int")
                        .HasColumnName("MesaID");

                    b.Property<int?>("SaloneroId")
                        .HasColumnType("int")
                        .HasColumnName("SaloneroID");

                    b.HasKey("OrdenId")
                        .HasName("PK__Orden__C088A4E4C9519D3B");

                    b.HasIndex("MesaId");

                    b.HasIndex("SaloneroId");

                    b.ToTable("Orden", (string)null);
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ProductoId")
                        .HasName("PK__Producto__A430AE83F0E98945");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.ProductoOrden", b =>
                {
                    b.Property<int>("ProductoOrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductoOrdenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoOrdenId"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("OrdenId")
                        .HasColumnType("int")
                        .HasColumnName("OrdenID");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    b.HasKey("ProductoOrdenId")
                        .HasName("PK__Producto__1E0C4908160B3405");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductoOrden", (string)null);
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReservaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<int?>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteID");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int?>("MesaId")
                        .HasColumnType("int")
                        .HasColumnName("MesaID");

                    b.HasKey("ReservaId")
                        .HasName("PK__Reserva__C3993703EC8E24E9");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MesaId");

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Salonero", b =>
                {
                    b.Property<int>("SaloneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SaloneroID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaloneroId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SaloneroId")
                        .HasName("PK__Salonero__89429A4448497433");

                    b.ToTable("Salonero", (string)null);
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Factura", b =>
                {
                    b.HasOne("Proyecto_Restaurante.Models.Orden", "Orden")
                        .WithMany("Facturas")
                        .HasForeignKey("OrdenId")
                        .HasConstraintName("FK__Factura__OrdenID__05D8E0BE");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Orden", b =>
                {
                    b.HasOne("Proyecto_Restaurante.Models.Mesa", "Mesa")
                        .WithMany("Ordens")
                        .HasForeignKey("MesaId")
                        .HasConstraintName("FK__Orden__MesaID__01142BA1");

                    b.HasOne("Proyecto_Restaurante.Models.Salonero", "Salonero")
                        .WithMany("Ordens")
                        .HasForeignKey("SaloneroId")
                        .HasConstraintName("FK__Orden__SaloneroI__02084FDA");

                    b.Navigation("Mesa");

                    b.Navigation("Salonero");
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Producto", b =>
                {
                    b.HasOne("Proyecto_Restaurante.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("FK__Producto__Catego__7A672E12");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.ProductoOrden", b =>
                {
                    b.HasOne("Proyecto_Restaurante.Models.Orden", "Orden")
                        .WithMany("ProductoOrdens")
                        .HasForeignKey("OrdenId")
                        .HasConstraintName("FK__ProductoO__Orden__08B54D69");

                    b.HasOne("Proyecto_Restaurante.Models.Producto", "Producto")
                        .WithMany("ProductoOrdens")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__ProductoO__Produ__09A971A2");

                    b.Navigation("Orden");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Reserva", b =>
                {
                    b.HasOne("Proyecto_Restaurante.Models.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("FK__Reserva__Cliente__7D439ABD");

                    b.HasOne("Proyecto_Restaurante.Models.Mesa", "Mesa")
                        .WithMany("Reservas")
                        .HasForeignKey("MesaId")
                        .HasConstraintName("FK__Reserva__MesaID__7E37BEF6");

                    b.Navigation("Cliente");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Mesa", b =>
                {
                    b.Navigation("Ordens");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Orden", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("ProductoOrdens");
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Producto", b =>
                {
                    b.Navigation("ProductoOrdens");
                });

            modelBuilder.Entity("Proyecto_Restaurante.Models.Salonero", b =>
                {
                    b.Navigation("Ordens");
                });
#pragma warning restore 612, 618
        }
    }
}
